```
numpy
pandas
scikit learn
matplotlib
seaborn
```

In [1]:
# numpy - n dimensional arrays

import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
a.shape

(3, 3)

In [4]:
b = [[1,2,3],[4,5,6],[7,8,9]]
b

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
b.shape

AttributeError: 'list' object has no attribute 'shape'

In [6]:
np.random.randint(1,100,10)

array([21, 33, 47, 57, 11, 81, 12, 76, 18, 88])

In [7]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.sin([90,180,270])

array([ 0.89399666, -0.80115264, -0.17604595])

# EDA

##### getting data from web

In [11]:
import pandas as pd
url='https://raw.githubusercontent.com/juliencohensolal/BankMarketing/master/rawData/bank-additional-full.csv'
data = pd.read_csv(url,sep = ";") # use sep="," for coma separation. 
data.head()

age        job  marital    education  default housing loan    contact  \
0   56  housemaid  married     basic.4y       no      no   no  telephone   
1   57   services  married  high.school  unknown      no   no  telephone   
2   37   services  married  high.school       no     yes   no  telephone   
3   40     admin.  married     basic.6y       no      no   no  telephone   
4   56   services  married  high.school       no      no  yes  telephone   

  month day_of_week ...  campaign  pdays  previous     poutcome emp.var.rate  \
0   may         mon ...         1    999         0  nonexistent          1.1   
1   may         mon ...         1    999         0  nonexistent          1.1   
2   may         mon ...         1    999         0  nonexistent          1.1   
3   may         mon ...         1    999         0  nonexistent          1.1   
4   may         mon ...         1    999         0  nonexistent          1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  
0          93.994          -36.4      4.857       5191.0  no  
1          93.994          -36.4      4.857       5191.0  no  
2          93.994          -36.4      4.857       5191.0  no  
3          93.994          -36.4      4.857       5191.0  no  
4          93.994          -36.4      4.857       5191.0  no  

[5 rows x 21 columns]

In [12]:
data.shape

(41188, 21)

In [13]:
np.mean(data['age'])

40.02406040594348

In [14]:
np.min(data.age)

17

In [15]:
data['job'].value_counts()

admin.           10422
blue-collar       9254
technician        6743
services          3969
management        2924
retired           1720
entrepreneur      1456
self-employed     1421
housemaid         1060
unemployed        1014
student            875
unknown            330
Name: job, dtype: int64

In [17]:
data['marital'].value_counts(dropna = False)

married     24928
single      11568
divorced     4612
unknown        80
Name: marital, dtype: int64